env:
    global:
        - METADATA_STORAGE_API_STORAGE_TYPE=RDF-FILESYSTEM
        - METADATA_STORAGE_API_STORAGE_LOCATION="sandbox/collections.rdf"
language: python
python:
    - "3.5"
install:
    - pip install -r requirements.txt
    - python setup.py install

script: pytest tests.py