#!/bin/bash
echo "METADATA_STORAGE_API_STORAGE_TYPE: ${METADATA_STORAGE_API_STORAGE_TYPE}"
echo "METADATA_STORAGE_API_STORAGE_LOCATION: ${METADATA_STORAGE_API_STORAGE_LOCATION}"
METADATA_STORAGE_API_STORAGE_TYPE=XML-FILESYSTEM
METADATA_STORAGE_API_STORAGE_LOCATION=/mnt/C/Users/tyler/Documents/Github/ldr_metadatastorage/sandbox/collections.xml
APP_SAVE=$FLASK_APP
FLASK_APP=metadatastorageapi
python -m flask run
export FLASK_APP=$APP_SAVE
